version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - REDIRECT_URI=${REDIRECT_URI}
      - COOKIE_KEY=${COOKIE_KEY}
    volumes:
      - ./src:/usr/src/app/src
      - ./public:/usr/src/app/public
    command: npm run dev